### PR TITLE
Ensure expired() is set on processed certificates

### PR DESCRIPTION
**Pull request by dadrian**

### CODE REVIEW

**Comment by zakird** [comment]
This seems fine, althouhg I remain somewhat perplexed why we set this in the protobuf.

**Comment by dadrian** [comment]
I don't follow your comment, what would you suggest instead?

**Comment by zakird** [comment]
Not having an expired bit?

**Comment by dadrian** [comment]
And doing what instead? Calculating it on the fly during dumps and in esloader? How do you know if a delta needs to be generated?

**Comment by zakird** [comment]
We don't set it anywhere downstream. It's not in the schema anywhere. What goes into tags is based on the expiration in the certificates not this field.

**Comment by zakird** [comment]
What do you mean know if a delta needs to be set? Check if the fields we have set are incorrect, and  if they are, then set them?

**Comment by zakird** [comment]
I mean, it's not a problem, I've just never really understood.

**Comment by dadrian** [comment]
I meant during nightly dumps, we push a delta when a certificate changes from non-expired to expired, and update it's trust accordingly.

**Comment by zakird** [comment]
Sure. You have all the data you need to make they decision based in root
store status and expiration dates.

**Pull request merged**
